filepaths:
  processed_data_dir: data/processed/
  sku_stats_dir: data/sku_stats/
  cv_results_dir: data/cv_results/
  eval_results_dir: data/eval_results/
  eval_plots_dir: data/eval_plots/
  file_format: CSV
